### ISSUE TITLE
[BUG] InvalidOperationException when using the Copy method

### ISSUE THREAD

**Issue by eirielson** [KoenZomers/OneDriveAPI#24]
**Describe the bug**
Hi,
I'm trying to use Api's Copy method. But I am getting an InvalidOperationException. "An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set."

**To Reproduce**
1. Go to 'Demo Application', run and click on the Authorize button
2. Click on 'Copy' button
3. See error
```
   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request)
   at KoenZomers.OneDrive.Api.OneDriveApi.<SendMessageReturnHttpResponse>d__142.MoveNext() in D:\workspace\labs\OneDriveAPI\Api\OneDriveApi.cs:line 2015
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KoenZomers.OneDrive.Api.OneDriveApi.<SendMessageReturnBool>d__141.MoveNext() in D:\workspace\labs\OneDriveAPI\Api\OneDriveApi.cs:line 1973
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KoenZomers.OneDrive.Api.OneDriveGraphApi.<CopyItemInternal>d__60.MoveNext() in D:\workspace\labs\OneDriveAPI\Api\OneDriveGraphApi.cs:line 794
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KoenZomers.OneDrive.Api.OneDriveApi.<Copy>d__86.MoveNext() in D:\workspace\labs\OneDriveAPI\Api\OneDriveApi.cs:line 704
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KoenZomers.OneDrive.Api.OneDriveApi.<Copy>d__85.MoveNext() in D:\workspace\labs\OneDriveAPI\Api\OneDriveApi.cs:line 692
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KoenZomers.OneDrive.AuthenticatorApp.MainForm.<CopyButton_Click>d__27.MoveNext() in D:\workspace\labs\OneDriveAPI\Demo\MainForm.cs:line 376
```
ps: Create a file on the drive inside a "test"folder

**Expected behavior**
The created file should be copied into the folder

**Screenshots**
![image](https://user-images.githubusercontent.com/15846345/95989903-3dd41f00-0e01-11eb-9c9a-32043adf0f41.png)
![image](https://user-images.githubusercontent.com/15846345/95990057-6bb96380-0e01-11eb-9081-abdd772876a8.png)
![image](https://user-images.githubusercontent.com/15846345/95989934-49274a80-0e01-11eb-9618-c86d0e897826.png)

**Versions (please complete the following information):**
- OS: Windows 10
- OneDriveApi: master branch

**Comment by KoenZomers** [comment]
Thanks for the extensive information @eirielson . I can reproduce this. Looking into it.

**Comment by KoenZomers** [comment]
Found it and fixed it. Releasing new version now.

**Comment by KoenZomers** [comment]
Released. https://www.nuget.org/packages/KoenZomers.OneDrive.Api/2.3.1.1

Closing this issue. If the problem persists for you using this new version, feel free to reopen.
