### ISSUE TITLE
Download File

### ISSUE THREAD

**Issue by BurhanEyimaya** [KoenZomers/OneDriveAPI#9]
Hi,

Thank you for this great API.

But I have an issue on downloading files from OneDrive.
In your demo application I tried to upload a single file "Test.txt" to folder "Test\sub1\sub".
Upload completed with success.

But the download operation fails.
In error message it says
"Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host."

![capture](https://user-images.githubusercontent.com/7566250/34258346-94a02468-e66e-11e7-896b-5a65112e0137.PNG)

Thanks,
Burhan Eyimaya

**Comment by KoenZomers** [comment]
Hi Burhan,

Is there no inner exception with more information? Are you using a proxy? Can you capture a Fiddler trace while doing the download and see what's really happening on the wire? If you need help examining it, mail it to me privately as it will contain your refresh token which you should not publish publicly.

**Comment by BurhanEyimaya** [comment]
Hi Koen,
Thank you for your fast response.
Here is the full exception details
TYPE : System.Net.Http.HttpRequestException
MESSAGE: An error occurred while sending the request.
STACK TRACE:   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KoenZomers.OneDrive.Api.OneDriveApi.<DownloadItemInternal>d__106.MoveNext() in D:\Projects\MS\OneDriveAPI\Api\OneDriveApi.cs:line 1010
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KoenZomers.OneDrive.Api.OneDriveApi.<DownloadItemAndSaveAs>d__89.MoveNext() in D:\Projects\MS\OneDriveAPI\Api\OneDriveApi.cs:line 701
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KoenZomers.OneDrive.Api.OneDriveApi.<DownloadItem>d__87.MoveNext() in D:\Projects\MS\OneDriveAPI\Api\OneDriveApi.cs:line 675
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AuthenticatorApp.MainForm.<DownloadToButton_Click>d__25.MoveNext() in D:\Projects\MS\OneDriveAPI\Demo\MainForm.cs:line 337
---- inner exception ----------------------------------------
TYPE : System.Net.WebException
MESSAGE: The underlying connection was closed: An unexpected error occurred on a send.
STACK TRACE:   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
---- inner exception ----------------------------------------
TYPE : System.IO.IOException
MESSAGE: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
STACK TRACE:   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
---- inner exception ----------------------------------------
TYPE : System.Net.Sockets.SocketException
MESSAGE: An existing connection was forcibly closed by the remote host
STACK TRACE:   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
Also I have attached the Fiddler session file.
I think there is no traffic during the download.
Sorry I couldn't understand the problem.
Thanks,
Burhan Eyimaya



Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by BurhanEyimaya** [comment]
Hi,

Also I have tried to upload to the Apps folder.
`OneDriveApi.UploadFileToAppFolder("Save.sav");`
This works and uploads the "Save.sav" file to Apps folder.

But download fails.

```
OneDriveItemCollection oneDriveItems = await OneDriveApi.GetAppFolderChildren();
OneDriveItem oneDriveItem = oneDriveItems.Collection.Where(x => x.Name == "Save.sav").SingleOrDefault();
await OneDriveApi.DownloadItem(oneDriveItem, downloadDir);

```

Here oneDriveItems collection and oneDriveItem variables are valid so it can find the correct files, but download fails.
Could you please try to download a file from Apps folder?

Thanks,
Burhan Eyimaya

**Comment by KoenZomers** [comment]
Hi Burhan,

Downloading works fine here. I modified the demo application at the following lines to mimic your scenario:

[cid:image001.png@01D381C7.84745D90]
This works well and it nicely stores the LICENSE.md file I have in the App Folder on my OneDrive for Business:
[cid:image002.png@01D381C7.84745D90]
To my D: drive:
[cid:image003.png@01D381C7.84745D90]
The Fiddler trace you shared just contains the authentication part. It doesn’t show even attempting any operation after connecting.

The error indicates something is blocking your network traffic on your machine. Could there be a proxy, firewall or anti virus product on your machine blocking this traffic? Try it from another machine on another internet line.

Kind regards,

Koen

**Comment by KoenZomers** [comment]
@BurhanEyimaya any luck in getting it to work?

**Comment by BurhanEyimaya** [comment]
Hi Koen,

Thank you for your attention.
Yes it worked.
You are right it was a problem related to my network.
Thanks again, and sorry for this false warning.

**Comment by KoenZomers** [comment]
@BurhanEyimaya good to hear it's resolved. Thanks for confirming!
